### PR TITLE
Implement i18n

### PR DESCRIPTION
**Pull request by uahmed-assecor**
Ticket: [https://git.datev.de/mandat/backlog/-/issues/350](https://git.datev.de/mandat/backlog/-/issues/350)

### CODE REVIEW

**Comment by banxtv** [comment]
there seems to be an issue with some of the strings:
image

**Review by banxtv — APPROVED** [review]
looks good! strings are displayed properly now :)

**Comment by banxtv** [comment]
notes from call with usama:

- we still have dvint urls in the package-lock.json

we need to ensure that the project can be built on any machine (without connections to datev internal resources/registry)

**Comment by uahmed-assecor** [comment]
After discussing with Christian the Package lock file is fixed now and it does not contains url from dvint. Thanks :)

**Pull request merged**
